### PR TITLE
conformed physics to CR

### PR DESCRIPTION
**Pull request by joelwhuff**
If you're interested. I changed the track to an auto to demonstrate

Glad I stumbled upon this project, love what you did with this

### CODE REVIEW

**Comment by tomiy** [comment]
This is awesome! I wondered what the deal was with physics but could never find why it changed. I'll check the PR locally when i can.

Do you know why the square that you changed doesn't work in your first commit? I swear javascript at least used to follow PEMDAS...

**Comment by joelwhuff** [comment]
I honestly have no idea what's wrong with the square. I was comparing the line collision method to the canvasrider source and changing whatever was slightly different, by chance that turned out to be the last piece to the puzzle.

I've been working with your code for a little while, I want to set up live collabing servers with it, So I was dead set on figuring out the physics.

**Comment by tomiy** [comment]
That sounds awesome! Feel free to shoot me a DM on discord if you use it (tomiy#2021), i'd love to talk more about the project.
I tested the PR locally and it works well, and doesn't break anything else. I just added some cleanup so that the ghosts don't sperg out every time.

**Comment by joelwhuff** [comment]
Awesome, will do! I should have a test version up soon hopefully

**Pull request merged**
